### ISSUE TITLE
Hashing Error on Enhanced Ore Veins

### ISSUE THREAD

**Issue by ngrunwald** [jdsmith2816/emw#100]
During download of mods in webbajack, there is a hashing error while downloading **Enhanced Ore Veins 2K 8.0** and the install aborts. Manifest needs some update??

**Comment by jdsmith2816** [comment]
A new update is in the works that will fix the installer.  In the meantime check the pins in the emw channel of the WJ discord for an interim solution.

**Comment by ngrunwald** [comment]
Thanks, will do!
