### ISSUE TITLE
Vagrant Dress first person issue

### ISSUE THREAD

**Issue by Regret13** [jdsmith2816/emw#103]
**Describe the bug**
Going into first person with the Vagrant Dress equipped shows an entirely different outfit on the arms.

**To Reproduce**

1. Equip Vagrant Dress
2. Go to the first person

**Expected behavior**
Expected the first person model to show the Vagrant Dress

**Screenshots**
![Elder_Scrolls_V_Skyrim_Screenshot_2020 11 09_-_16 44 28 18](https://user-images.githubusercontent.com/74215529/98603694-81ab2e80-22b0-11eb-8793-bc3c09d5f2e0.png)
![eefad34ab1c9bbba2e542bc4b28b10eb-png](https://user-images.githubusercontent.com/74215529/98603719-8f60b400-22b0-11eb-89b7-5f760bcdee5e.jpg)

**Modlist version**
1.0.11
**Did you add any additional mods?**
Only added the full inu Lord Nicholas armor mod. It's not a replacer, just a new set of armor.

**Comment by jdsmith2816** [comment]
This is no longer an issue for the upcoming release.
