### ISSUE TITLE
**Calia Spoilers**

### ISSUE THREAD

**Issue by Regret13** [jdsmith2816/emw#108]
**Describe the bug**
https://youtu.be/-uTrlD93Rn0?t=1029 This scene doesn't work as intended. Both actors just kind of stand there.

**To Reproduce**

This happens in old Dothulgrad during the Deus Ex Machina quest. Just go along the quest until you reach this point.

**Expected behavior**
Expected the animation to play out as intended but both actors just stand and stare at each other.

**Screenshots**
https://gyazo.com/0df6c58a01c3b872e7549b74d4e00469
**Modlist version**
1.0.11
**Did you add any additional mods?**
Just an additonal armor set.

**Comment by shazdeh** [comment]
Can confirm this bug (also using 1.0.11). I was so confused by their later dialog!
