### ISSUE TITLE
Adding 'Smart Cast' to modlist

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#11]
**Request**
It is a great mod for qol improvement for casting.  You can automate your spells, for example casting an armor buffing spell when drawing your weapon or healing  under a certain hp treshold without having to equip/unequip those spells and thus not having to pause the game to go into your menu and interupting the combat 'flow'.

**Additional context**
https://www.nexusmods.com/skyrim/mods/43123

**Comment by jdsmith2816** [comment]
Feel free to add this to your personal version of EMW but I'm opting not to include it in the main list.  

There's an aspect of player skill that gets lost when the spells always just work for you without thought.  Some of magecraft is balanced around the cases of forgetting to use things like your flesh spells and stuff like that.  I'm not sure taking away that aspect of gitgud for everyone is the right choice.
