### ISSUE TITLE
Wabbajack installation fail

### ISSUE THREAD

**Issue by Juswannaplay** [jdsmith2816/emw#110]
**Describe the bug**
I continuously get an error when trying to download EMW with wabbajack, the same one as someone previously had in a closed issue, saying unable to download: GameFileSourceDownloader + State|enderal 1.9.32.0| Data\ E-scripts.bsa"
as well as GameFileSourceDownloader + State|enderal 1.9.32.0| Data\ E-Meshes.bsa

I did try to find a solution by scouring the issues section but the only thing I could find was that it was fixed in the latest update, though that doesnt seem to be the case for me
Please let me know if there is something that I am doing wrong that's causing this, I am really looking forward to trying this modlist out

**To Reproduce**
follow installation instructions, fails to download the files mentioned above during the wabbajack download.

**Expected behavior**
Expected to download and install as normal

**Modlist version**
presumably the latest, whichever one was the direct download off of wabbajack

**Did you add any additional mods?**
I haven't had a chance to even try it as it is lol

**Comment by Caldelan** [comment]
Having the same issue just now.

![Capture](https://user-images.githubusercontent.com/75386138/100907924-30671700-34cb-11eb-9013-6cb336c655ea.PNG)

**Comment by wow420** [comment]
Hi, same here. Also noticed there are some issues with downloading [Alpha] BDO Complete Pack by Team TAL thru wabbajack, so i tried to download it manually (BDO Complete Pack from FAQ) and put it inside the download folder
![image](https://user-images.githubusercontent.com/75396878/100938334-ce230c00-34f4-11eb-8b98-6daae34566e5.png)

![image](https://user-images.githubusercontent.com/75396878/100938389-e430cc80-34f4-11eb-9464-df041b1d3033.png)

Completely removed wabbajack and downloaded a new one from the page. Started new installation at least three times.
Blame myself for the decision to re-install the build :D

**Comment by Juswannaplay** [comment]
my guess is the patch for enderal that was released on the 29th has changed something about those 2 files that is causing this issue, since by all accounts it appears this issue *was* fixed in the most recent update of EMW, but is now presenting a problem again. Hopefully it wont take too long to surmise a solution, for now I will just play vanilla enderal and check back here periodically

**Comment by Caldelan** [comment]
No idea what changed but i tried again and it seems to work now

**Comment by Juswannaplay** [comment]
Yep, I can also confirm it is indeed working again now. That's awful strange but im happy nonetheless. Im not sure if I should leave this open or not so I will leave that to JD's discretion

**Comment by keindu** [comment]
Ello - having a problem along this vein. Any ideas? Thank you!
![image](https://user-images.githubusercontent.com/75495785/101193577-03754a00-361a-11eb-9a54-c86654c9015b.png)

**Comment by Juswannaplay** [comment]
I'm not sure man, after the other guy commented that it was working again I tried and it worked immediately, I had to delete and reinstall the BDOR pack that was mentioned earlier, and the rest worked just fine

**Comment by keindu** [comment]
ahh too bad - I am basically just rerunning over and over hoping it eventually works xD

**Comment by keindu** [comment]
could someone explain what the BDOR pack means? Is that the manual file from github, rather than the wabbajack browse list?

**Comment by keindu** [comment]
current problem is: 
![image](https://user-images.githubusercontent.com/75495785/101227529-66d09d80-3655-11eb-8cb5-4dad4de281ad.png)

**Comment by keindu** [comment]
Update: Delete and reinstall BDO Complete Pack from the FAQ link found at the bottom of the page here: https://www.wabbajack.org/#/modlists/info?machineURL=emw . Worked for me. GL :)

**Comment by davidp57** [comment]
Worked perfectly, thanks for the tip

**Comment by Zeludon** [comment]
I am having a similar but different issue on install, these nexus mods will not install even when manually downloaded and placed in the downloads folder.

![image](https://user-images.githubusercontent.com/7567017/105616026-f1e53d00-5e27-11eb-8630-13404fcee36c.png)

**Comment by jdsmith2816** [comment]
The list is definitely currently installable.  If you're still in need of help with this please reach out on the discord server in the #emw-support channel
