### ISSUE TITLE
Headgear "Glance of the Swashbuckler" and "Swashbuckler Hair [F]" do not render correctly

### ISSUE THREAD

**Issue by tslaton** [jdsmith2816/emw#113]
1. When equipped by itself "Glance of the Swashbuckler" (ARMO: 00032778) is invisible, as pictured.
![20210130111738_1](https://user-images.githubusercontent.com/9665562/106365847-155b2c80-62ed-11eb-821f-85d5a1a02e1b.jpg)
2. When equipped by itself "Swashbuckler Hair [F]" (ARMO: 5400081E) has a gap between the ponytail and head, as pictured.
![20210130104853_1](https://user-images.githubusercontent.com/9665562/106365507-f65b9b00-62ea-11eb-831e-f988849fef85.jpg)
3. When equipped together (which the in game art suggests ought to fill the gap in the ponytail?), the character's hair is incorrectly rendered as a balding male's hair, as pictured.
![20210130104906_1](https://user-images.githubusercontent.com/9665562/106365575-50f4f700-62eb-11eb-853e-d9155e16f768.jpg)

My character's race is Half-Kilenian, and her base hairstyle is no. 9 in the character creation menu, called "1Cassy."

As far as I recall, I started playing this character at v1.0.9, and had the same issues back then. I just now updated to v1.0.11, and the issue persists. First shot is with the regular (low-poly) head, and the second two are using the high-poly head. It doesn't seem to make a difference in any of the issues.

**Comment by jdsmith2816** [comment]
Thanks for the detailed report.  This issue will not be present in the next update.
