### ISSUE TITLE
Wabbajack installation fail. 

### ISSUE THREAD

**Issue by Nernx** [jdsmith2816/emw#114]
**Describe the bug**
First time install. I followed everything on the install guide. After 2-3 hours of trying again and again It would not download files needed to finish the install. I tried downloading certain mods manually and placing them into the download location which works but certain mods are either not showing up when looking for them or hidden from viewing. Please recheck the modlist again, please. I would really love to use this, TBH I only wanted Combat Gameplay Overhaul to work with enderal. but I would love to use all these mods. So please if there is any way to patch this please do. Ty for your hard work

**To Reproduce**

1. Go to Wabbajack and press install from disk
2. wait to finish downloading

**Expected behavior**
Installation failed 
**Screenshots**
Screenshot 1: 
![image](https://user-images.githubusercontent.com/78445131/106656793-11503880-6593-11eb-9699-2297b03fd6e2.png)
ScreenShot 2: Mods that where failing to download.
![image](https://user-images.githubusercontent.com/78445131/106656865-29c05300-6593-11eb-9193-7067a9aa3d07.png)
ScreenShot 3 : Mods that cant be found or hidden 
![image](https://user-images.githubusercontent.com/78445131/106656971-54121080-6593-11eb-8364-42f0f82c127b.png)

**Modlist version**

**Did you add any additional mods?**
no extra mods added only the once that was failing to download

**Comment by jdsmith2816** [comment]
The game is definitely still installable.  Try again.  If you're still having troubles please reach out on the discord server for assistance in the #emw-support channel.
