### ISSUE TITLE
Iron shield changes visuals when in the player's back

### ISSUE THREAD

**Issue by guto8797** [jdsmith2816/emw#117]
The Iron shield goes from a heater-type shield to a round shield. 

Minor visual issue.

![SkyrimSE 2021-02-26 15-57-35](https://user-images.githubusercontent.com/7987524/109323681-a6211b80-784b-11eb-8593-52fc336ffe51.png)
![SkyrimSE 2021-02-26 15-57-56](https://user-images.githubusercontent.com/7987524/109323731-b0dbb080-784b-11eb-8407-b9063a633df2.png)

**Comment by jdsmith2816** [comment]
Resoled in 2.0.1
