### ISSUE TITLE
Animation glitch with bow bash

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#12]
**Describe the bug**
 while being in 3rd person and blocking (hiting) with the bow whilst running results in a glitched leg animation.
Only happens of course, if you have enough stamina to bash with the bow.

**To Reproduce**
everytime reproducable like described

**Expected behavior**
no glitch

**Screenshots**
-

**Modlist version**
1.0.1.

**Did you add any additional mods?**
nope

**Comment by jdsmith2816** [comment]
Fixed in 1.0.3
