### ISSUE TITLE
The Ripper texture error

### ISSUE THREAD

**Issue by uphurp** [jdsmith2816/emw#123]
**Describe the bug**
Texture error with the weapon named The Ripper. It appears bright purple when lying on the ground but has the correct texture when equipped.

**To Reproduce**
1. Equip The Ripper.
2. Unequip and drop The Ripper on the floor

**Expected behavior**
The weapon model should have the correct texture.

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.
https://puu.sh/HnANZ/e4d8df6cd9.jpg <-screenshot

**Modlist version**
2.0.3
**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in EMW v2.0.4
