### ISSUE TITLE
Dagger of Despair- 1st Person Shield clipping 

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#128]
![SkyrimSE 2021-03-19 09-28-34](https://user-images.githubusercontent.com/69637298/111752451-0416b100-8896-11eb-8eec-cd9d07b9ade9.png)
![SkyrimSE 2021-03-19 09-28-36](https://user-images.githubusercontent.com/69637298/111752474-0da01900-8896-11eb-93c7-55a6ee05ac76.png)
![SkyrimSE 2021-03-19 09-29-25](https://user-images.githubusercontent.com/69637298/111752499-155fbd80-8896-11eb-8a77-276414489880.png)
![SkyrimSE 2021-03-19 09-29-52](https://user-images.githubusercontent.com/69637298/111752524-1bee3500-8896-11eb-92a2-7016f8b021da.png)

**Comment by jdsmith2816** [comment]
Fixed in EMW v2.0.4
