### ISSUE TITLE
Add Steam Version Time&Achievement Tracking mod of Enderal SE

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#129]
![image](https://user-images.githubusercontent.com/69637298/111761865-a89df080-88a0-11eb-9ac2-389b455717dc.png)

https://www.nexusmods.com/enderalspecialedition/mods/1/?tab=files

**Comment by jdsmith2816** [comment]
This has been added in EMW v2.0.4 as an optional disabled-by-default mod due to having no way of knowing who has EFSSE in their Steam Library.
