### ISSUE TITLE
Fast travel and other economy related issues.

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#13]
Money is meant to be hard to get in the game. So, looting a dungeon and what you carry back is meant to be well thought out. Being able to fast travel back and for the easily from dungeons to town, breaks that.

There is a spellbook in the player house in the marketplace that allows you to send all your loot to the house. Same problem.

However, EGO adds insult to injury by getting rid of Secure Chests from marketplaces, and that is a problem. What is interesting, is that two Secure CHests are left, one in the abandoned house in Riverville, and one in the ruin that you can convert into a house early on in the Sun Coast... those should be left alone.

In order to not make life too hard, I would have the merchants in Riverville sell "Teleport to Riverville" spells for 50 pennies (as opposed t the 100+ that they normally cost, so that adventuring in the early part of the game isn't too tedious.

**Comment by jdsmith2816** [comment]
Resolved in 1.0.2.  Thanks for the feedback.
