### ISSUE TITLE
Swap "Water for ENB" for "SkyVRaan"

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#130]
ENB water looks not right with the water meshes.

**Comment by kratores85** [comment]
![image](https://user-images.githubusercontent.com/69637298/112183507-9bfdfd00-8bfe-11eb-83c5-5cbba5011e5e.png)
"Water for ENB" - textures only

**Comment by kratores85** [comment]
ENB water somehow causes ugly tearing effects on reflections - I would recommend shipping enbseries.ini with "Water" disabled

**Comment by kratores85** [comment]
For proper SSR, use ENB. You may need to remove fWaterSSRIntensity=0.0001 then.

**Comment by kratores85** [comment]
Improves LOD-Water seams greatly, also the flickering / shimmering ENB Water is reduced significantly
![2](https://user-images.githubusercontent.com/69637298/113899986-a3600180-97cd-11eb-8a15-7885476bb3d1.jpg)

**Comment by kratores85** [comment]
![image](https://user-images.githubusercontent.com/69637298/114046904-8426aa00-9889-11eb-9614-11f4953bd9ac.png)
Enabling this option messes up the colors from these waters..
![SkyrimSE 2021-04-08 16-31-40](https://user-images.githubusercontent.com/69637298/114046999-9e608800-9889-11eb-8b8f-60403f9df4cd.png)

**Comment by kratores85** [comment]
@jdsmith2816 another option would be RW2 + Water for ENB (just textures).. LOD water doesn't get improved but the bright waterfall fix works at least ;)

**Comment by kratores85** [comment]
To improve the LOD-Water AND the Bright waterfalls I installed SkyVRaan AND Water for ENB - both with textures&meshes:
The Bright Waterfall Fix isn't needed since I use the one in the installer of Water for ENB

![image](https://user-images.githubusercontent.com/69637298/114134287-c8588f80-9907-11eb-82ad-911d892c7ad7.png)

![enb2021_4_9_07_39_58](https://user-images.githubusercontent.com/69637298/114134161-92b3a680-9907-11eb-84de-c101cf92e9f3.jpg)
![enb2021_4_9_07_44_19](https://user-images.githubusercontent.com/69637298/114134163-934c3d00-9907-11eb-82fc-d634207e23ac.jpg)

**Comment by jdsmith2816** [comment]
Fixed in EMW v2.1
