### ISSUE TITLE
Add "Violens - Killmove"

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#134]
This is soooo nice:
https://www.nexusmods.com/skyrimspecialedition/mods/668

**Comment by kratores85** [comment]
Here's my recommended profile, so that KM aren't too dominant over normal kills ;)
[Kratores_Killmoves.zip](https://github.com/jdsmith2816/emw/files/6195133/Kratores_Killmoves.zip)

**Comment by kratores85** [comment]
This mod breaks things! (EGO probably disables killmoves)

**Comment by jdsmith2816** [comment]
I'll pass
