### ISSUE TITLE
Add "SkyHUD"

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#135]

**Comment by kratores85** [comment]
Maybe "Dark" version and Custom position also is an option..?

**Comment by kratores85** [comment]
No.. the shipped HUD looks better imo..

**Comment by kratores85** [comment]
Makes HUD cleaner and less intrusive
![image](https://user-images.githubusercontent.com/69637298/112346877-ab487d80-8cc6-11eb-8227-415cd4385d11.png)
![image](https://user-images.githubusercontent.com/69637298/112346963-c3200180-8cc6-11eb-8bda-bb6bd3c0c84b.png)
![image](https://user-images.githubusercontent.com/69637298/112347718-653fe980-8cc7-11eb-8eb4-e690a1509cb1.png)

**Comment by Fjodik** [comment]
Fully support this request, would be a great addition, thank you.

**Comment by jdsmith2816** [comment]
Done in 2.1.1
