### ISSUE TITLE
Stuck in low resolution

### ISSUE THREAD

**Issue by SirDrexx** [jdsmith2816/emw#137]
**Describe the bug**
Everything set to 1080p but resolution is extremely low once I load up the game.

I have tried everything to fix this I am lost.

**Expected behavior**
Expected resolution to be higher, unknown issue messing up my game.
**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**
Most recent wabbajack version
**Did you add any additional mods?**
No

**Comment by kratores85** [comment]
@SirDrexx Set 
Resolution=SetYourNativeResolutionHere
ResolutionScale=1.00
in  EMW\mods\Display Tweaks - EMW Config\SKSE\Plugins\SSEDisplayTweaks.ini
@jdsmith2816 I think you can close this issue ;)
