### ISSUE TITLE
Ark Bank Vault CTD

### ISSUE THREAD

**Issue by BeefFillet** [jdsmith2816/emw#139]
**Describe the bug**
Reproduce-able CTD at the Ark Bank Vault.

**To Reproduce**

1. Go to Ark Bank Vault inside the Ark Bank.
2. Walk up the stairs to your vault.
3. CTD may happen at varying locations of the vault.

**Expected behavior**
Sometimes the CTD occurs when you walk up the first set of stairs or sometimes it occurs once you've reached the uppermost floor of the vault.

I only noticed this CTD after I did the ceremony to become a keeper. This may or may relate to the bug. Did some testing and reloaded a save before I became a keeper and the CTD did not happen. This may just be a coincidence, however. With the console, I realized the CTD doesn't happen if I disable all the Ark Bank Vault Guards/kill-all them. Perhaps it has to do with their animations? I only tested this because I noticed that the Ark City Guard came up multiple times in different crash logs. 

On a side note, the guard's patrol pathing in the uppermost level of the Ark Bank Vault is bugged. Basically, the guard gets stuck walking into a cell gate. Not sure if that was relevant.

**Screenshots**

**Modlist version**
2.0.4

**Did you add any additional mods?**
Nope
[Crash_2021_4_1_3-41-43.zip](https://github.com/jdsmith2816/emw/files/6275458/Crash_2021_4_1_3-41-43.zip)

**Comment by BeefFillet** [comment]
UPDATE: I'm still getting the CTD despite consoling out the guards in the vault. Guess that's not the cause of the bug.

**Comment by jdsmith2816** [comment]
Fixed in EMW v2.1.0
