### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#14]
![image](https://user-images.githubusercontent.com/18401877/82756760-cca9b600-9de4-11ea-8c83-645455ffd93b.png)

**Comment by Lazasar** [comment]
Old Dam Lookout
![image](https://user-images.githubusercontent.com/18401877/82756823-35912e00-9de5-11ea-9a25-1e3ffa3bb5d1.png)

**Comment by jdsmith2816** [comment]
Everything above this fixed in 1.0.2

**Comment by jdsmith2816** [comment]
Going to go ahead and close. If you find more you can re-open this issue with them or make a new ticket.  Thanks!
