### ISSUE TITLE
CTD after talking to Alfred in Riverville.

### ISSUE THREAD

**Issue by YeNZeC** [jdsmith2816/emw#143]
CTD after talking to Alfred in Riverville.

Follow the main story, first 3 hours in or so, you'll get to Alfred, a essential character to progress to ARK with Jespar, CTD after the last voice line is prompt.

**Comment by jdsmith2816** [comment]
@YeNZeC Please include a savefile (both the .skse and .ess file) and a crashlog when making a bug report such as this.  I've done this multiple times without problem so I'm hesitant to invest the time to reproduce it at the moment.

**Comment by jdsmith2816** [comment]
Cannot reproduce in 2.1.1
