### ISSUE TITLE
Cobwebs too bright

### ISSUE THREAD

**Issue by Marvin36** [jdsmith2816/emw#148]
**Description:**
The cobwebs are too bright, only noticed indoors on FxcobwebCorner02.nif so far. Maybe caused by 'Rudy HQ - Enderal Mesh and Texture Fixes' (modifies this specific file) or 'Spider Webs and Particles for ENB', though I am not sure.

**Steps to reproduce the behavior:**
Go into any interior with cobwebs.

**Screenshots**
![The Elder Scrolls V  Skyrim Special Edition Screenshot 2021 04 14 - 20 58 31 28](https://user-images.githubusercontent.com/60287937/114765326-5350e400-9d65-11eb-90e4-c1271a6fb3be.png)

**Modlist version**
2.1.1
**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Fixed in 2.1.2
