### ISSUE TITLE
Adding 'Mortal Enemies' to modlist

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#15]
**Request**
Adding the mod 'Mortal Enemies' 
"Improves Skyrim's combat by removing the ultra-precise aimbot attacks of Creatures, and imposing movement limits on Humanoid NPCs while they are attacking!" from the mod description.
Enemies now have a turn rate and have a more balanced attack arc. This mod uses afaik no scripts.

**Additional context**
https://www.nexusmods.com/skyrim/mods/73921/

**Comment by jdsmith2816** [comment]
We already make use of a customized version of mortal enemies.
