### ISSUE TITLE
Add "KenMOD" System time on loadscreens

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#150]
Already tested this, works fine in Enderal SE / EMW ;)

Looks like this - I personally like it
![enb2021_4_17_12_07_52](https://user-images.githubusercontent.com/69637298/115109383-c5981300-9f75-11eb-9477-f941f4e7c053.jpg)

**Comment by kratores85** [comment]
Sure, the frame around the picture's gone but this is so useful for keeping time in eye :)

**Comment by jdsmith2816** [comment]
I'll pass.
