### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by Lewlet** [jdsmith2816/emw#151]
**Describe the bug**
Wabbajack installation failed because the mod (WS Modules for Lighting Mods) is not on nexusmods and can not be downloaded.

**To Reproduce**
Install the mod list with wabbajack.

**Expected behavior**
Installation of the mod list.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/40758720/115139996-67a02400-a078-11eb-8f29-5602d90b26c1.png)

**Modlist version**
2.4.3.3

**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
The latest installer works fine
