### ISSUE TITLE
Broken animation in deus ex machina

### ISSUE THREAD

**Issue by Morbidetto** [jdsmith2816/emw#152]
**Describe the bug**
Caria animation in deus ex machina is broken and it seems to be caused by nemesis. Cutscene progresses but animation doesn't play out, Caria and Karek  are mostly standing still when they suppose to fight

**To Reproduce**
[Saves.zip](https://github.com/jdsmith2816/emw/files/6331052/Saves.zip)
2 saves attached, 401 is just before animation plays out, 394 is earlier -> need go to passage and then all the way left
394 doesn't crash when used with vanilla enderal so it's useful for testing
When I disable all nemesis related mods  -> it works
When I disable all animation mods, enable enderal behavior pack and nemesis only, generate clean nemesis output -> it doesn't work
Managed to reproduced it also on vanilla copy of Enderal
1. Install Enderal SE on Steam -> Cutscene works
2. Install Enderal Behavior Pack -> Cutscene works
3. Install Nemesis and generate the files -> Cutscene is broken
I also tested it out with FNIS instead of Nemesis -> It works then

**Expected behavior**
Animation should play out as in vanilla

**Modlist version**
2.1.2

**Did you add any additional mods?**
No, but I have all EGO mods disabled and I'm using esp version of flora fixes

**Comment by jdsmith2816** [comment]
Unfortunately we can't fix this one;  I have found no way to have that cutscene not break with Nemesis and Nemesis is too integral to the modlist.  You'll have to watch that cutscene on Youtube.
