### ISSUE TITLE
Change gourds back to traditional pumpkin-models

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#153]
Tree Model

![image](https://user-images.githubusercontent.com/69637298/115423193-e83c5d00-a1fd-11eb-86f3-1b97c32a8c47.png)
![image](https://user-images.githubusercontent.com/69637298/115424540-166e6c80-a1ff-11eb-960f-504eeef1eb70.png)

Ingestible Model
![image](https://user-images.githubusercontent.com/69637298/115425436-ea9fb680-a1ff-11eb-9b26-4b7c7a72b543.png)
![image](https://user-images.githubusercontent.com/69637298/115425747-2d618e80-a200-11eb-9a96-583b7b4a298c.png)

Version 2.1.2

**Comment by kratores85** [comment]
It's from Cathedral - Plants (gourd01.dds)

**Comment by kratores85** [comment]
nvm..

**Comment by kratores85** [comment]
![image](https://user-images.githubusercontent.com/69637298/115423193-e83c5d00-a1fd-11eb-86f3-1b97c32a8c47.png)

![image](https://user-images.githubusercontent.com/69637298/115423225-ee323e00-a1fd-11eb-8a77-6624bd31de0f.png)

**Comment by jdsmith2816** [comment]
Fixed in next version
