### ISSUE TITLE
Minor Issue: male mage robes remesh from asset replacer not correctly displaying unique colors for mage robes in Enderal

### ISSUE THREAD

**Issue by firydoom3** [jdsmith2816/emw#155]
The remesh of the male mage robes form the asset replacer isn't correctly displaying the alternate textures of the robes (the red for novice keepers, white for keepers, etc.) when worn, but is correctly displaying them in the inventory
when worn they only display the base collage robe texture depicted 
![Mantled_College_Robes_ver1](https://user-images.githubusercontent.com/82637283/115314539-01300a00-a13b-11eb-8774-d1f260a97793.png)

**Comment by jdsmith2816** [comment]
Reverted mage robes in EMW AR for now until I can spend time to actually figure the issue out.
