### ISSUE TITLE
Add "Wood&Paper" skin for Dear Diary

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#159]
https://www.nexusmods.com/skyrimspecialedition/mods/44174?tab=images

Here's the patch for Enderal SE discord.
[Dear_Diary_EnderalSE_patch.zip](https://github.com/jdsmith2816/emw/files/6345377/Dear_Diary_EnderalSE_patch.zip)

**Comment by kratores85** [comment]
Hero Panel wasn't updated

**Comment by kratores85** [comment]
Waiting for hero menu update

**Comment by kratores85** [comment]
MO2 prio
![image](https://user-images.githubusercontent.com/69637298/115444412-d1edcb80-a214-11eb-8b9f-f464054344d5.png)

**Comment by jdsmith2816** [comment]
Added as disabled by defaul tin next release
