### ISSUE TITLE
Can't install v1.0.2 - Error with Kids of Enderal download

### ISSUE THREAD

**Issue by mael5trum** [jdsmith2816/emw#16]
**Describe the bug**
There is an error when trying to complete installation regarding downloading Kids of Enderal-93432-1-5-1552646531.zip
Even though the download completes and I've even downloaded the files manually but still get the same error.
This is while using the most recent version of Wabbajack v2.0.6.1

**Comment by mael5trum** [comment]
Tried deleting Wabbajack %appdata/local files and redid file hashing but it's still getting me to download the Kids of Enderal Files that I already have after which it errors out again.

**Comment by jdsmith2816** [comment]
I put out a fresh installer that should resolve this problem.  Let me know?

**Comment by mael5trum** [comment]
Tried it out with the new installer and it finishes installing now.
Thanks for all the great modlists.

**Comment by jdsmith2816** [comment]
No problem.  Let me know how it goes. :)
