### ISSUE TITLE
Different objects not displaying textures correctly

### ISSUE THREAD

**Issue by firydoom3** [jdsmith2816/emw#160]
wooden portcullis are not displaying the texture from the underground mod correctly, using the textures from ruins clutter improved works, or removing the mesh from ruins clutter improved also works
![enb2021_4_20_14_16_05](https://user-images.githubusercontent.com/82637283/115454321-465d4600-a1e6-11eb-8a14-67ae074c6c68.png)

**Comment by firydoom3** [comment]
The chopping block from Skyrim 3D Misc - Chopping Block and Axe doesn't correctly display textures for bloody or snowy blocks, using this mod fixes the issue https://www.nexusmods.com/skyrimspecialedition/mods/34915

**Comment by firydoom3** [comment]
Barrels in the undercity using the file Barrel02.nif from awesome HD Barrels do not display their texture correctly

**Comment by jdsmith2816** [comment]
These issues are resolved in the next update;  thanks!
