### ISSUE TITLE
HP bar again gets hidden when HP not full

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#161]
EMW 2.1.2

**Comment by kratores85** [comment]
[saves.zip](https://github.com/jdsmith2816/emw/files/6349843/saves.zip)

**Comment by jdsmith2816** [comment]
Does the issue go away if you disable skyhud

**Comment by kratores85** [comment]
Yes, it's SkyHUD related.. sadly the bars are so huge without that mod :(
![enb2021_4_22_09_07_41](https://user-images.githubusercontent.com/69637298/115670905-39596780-a34a-11eb-86ed-4e2cbfaf9a66.png)

**Comment by jdsmith2816** [comment]
You said you verified this wasn't a problem which is the only reason SkyHUD was added.. now I have to remove it.

![image](https://user-images.githubusercontent.com/556678/115728798-aa445380-a339-11eb-84dd-22cb9af5a96f.png)

**Comment by kratores85** [comment]
I installed Patch - SkyHUD v090B and Immersive HUD Patch v2, too that time.. maybe that's the problem, but nvm.. I'll retest this some time
