### ISSUE TITLE
Strange pile texture near Old Dam Lookout

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#163]
![pile1](https://user-images.githubusercontent.com/69637298/115555235-918f5b80-a2af-11eb-9209-4c4d9ac36c18.jpg)
![pile2](https://user-images.githubusercontent.com/69637298/115555278-9c49f080-a2af-11eb-9c45-6b6e47c16ce2.jpg)

**Comment by jdsmith2816** [comment]
I don't know how to fix this;  ENB affects decals in a way that I don't know how to fix.  If you turn ENB off you'll see the border disappear.

**Comment by kratores85** [comment]
OK.. It's steamin ENB I use.. so I'll close this one for now
