### ISSUE TITLE
Problem with textures/meshes on a barrel

### ISSUE THREAD

**Issue by Fjodik** [jdsmith2816/emw#164]
**Describe the bug**
One barrel on the ship at the beginning of the game has wrong meshes/textures. This is the place when you meet the veiled woman.

**To Reproduce**

**Expected behavior**
textures/meshes on the barrel not broken

**Screenshots**
![enb2021_4_24_12_04_54](https://user-images.githubusercontent.com/63248466/115955942-17064c00-a4fa-11eb-8c49-e1c57dc1785a.jpg)
![enb2021_4_24_12_04_48](https://user-images.githubusercontent.com/63248466/115955944-18377900-a4fa-11eb-8e5d-83c8b45358dc.jpg)

**Modlist version**
EMW 2.1.2

**Did you add any additional mods?**
No

**Comment by kratores85** [comment]
Noticed this on my testsave, too ;)

**Comment by jdsmith2816** [comment]
Fixed in next update
