### ISSUE TITLE
Texture missing in own house in arc marketplace

### ISSUE THREAD

**Issue by aldarund** [jdsmith2816/emw#166]
**Describe the bug**

**To Reproduce**
Go to bough house in arc marketplace

**Expected behavior**
Table and so texture seems to be missing

**Screenshots**

![SkyrimSE 2021-04-25 14-56-13](https://user-images.githubusercontent.com/571159/115992476-9406f380-a5d6-11eb-854f-c3a1a3054cf5.png)
![SkyrimSE 2021-04-25 14-56-01](https://user-images.githubusercontent.com/571159/115992487-98cba780-a5d6-11eb-87ed-a03d6490f2d6.png)
![SkyrimSE 2021-04-25 15-59-32](https://user-images.githubusercontent.com/571159/115994348-4b076d00-a5df-11eb-9bd5-71f1e4179e26.png)

**Modlist version**
2.1.2

**Did you add any additional mods?**
no

**Comment by guf616** [comment]
This isn't a bug, it's actually intended!  The house isn't fully completed until you buy the furniture upgrade for 300 pennies.  Make sure you do that first!

**Comment by aldarund** [comment]
Hm, how that make sense? There just flying pans, boxes etc.

**Comment by guf616** [comment]
Once you get the furniture upgrade, all of the missing furniture will appear and the house will appear as normal.

**Comment by jdsmith2816** [comment]
> Hm, how that make sense? There just flying pans, boxes etc.

Basically the mod author was lazy and didn't tag his additional clutter to enable only when the purchased stuff get's enabled.  One of these years I'll fix it in the replacer esp..
