### ISSUE TITLE
Duneville burnt cart - disable glowing/burning effect

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#167]
PI-CHO ENB
![ScreenShot53](https://user-images.githubusercontent.com/69637298/116429798-83f54b00-a846-11eb-8d36-5045ac0778dc.png)

STEAMIN ENB
![enb2021_4_28_17_12_47](https://user-images.githubusercontent.com/69637298/116429880-966f8480-a846-11eb-968f-c247c60d3141.png)

Cart-ID
![ScreenShot54](https://user-images.githubusercontent.com/69637298/116429829-8a83c280-a846-11eb-9e88-ca22a1c51059.png)

**Comment by kratores85** [comment]
Fix: https://www.nexusmods.com/skyrimspecialedition/mods/16982

**Comment by jdsmith2816** [comment]
Fixed in next update by re-installing the included woodfires mod and choosing no glow.
