### ISSUE TITLE
Add "All Geared Up Derivative - JS Purses and Septims Patch"

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#168]
For consistency with JS Purses and Septims.

**Comment by jdsmith2816** [comment]
Enderal uses a different currency so I had to edit the JS Purses and Septims to reflect this.  We only use the money bags and that mesh had the uv and texture paths updated for enderal money textures.

I didn't include the ALLGUD patch for this as I didn't feel like editing the 40 or so nif's it uses.  One of these days maybe.  There's no reason you couldn't be sporting a different money bag on your hip than the ones you find laying about.  Your fashion sense is just a bit different. ;)

**Comment by LoD7995** [comment]
That's a fair point, even though you must have a keen eye to spot this. But then at least the "moneybag01.dds" texture from "Rustic Clutter Collection" could be used instead. The septims that are present in the texture aren't actually used by the meshes or anywhere else ingame afaik.

coinbaglarge.nif for example:

![coinbaglarge nif - NifSkope 2 0 Dev 7 03 05 2021 00_33_58](https://user-images.githubusercontent.com/83468628/116829944-49bddd80-aba7-11eb-9955-c67e250de6b9.png)

**Comment by jdsmith2816** [comment]
Hmmmm tbh the fact that it has different coins is probably irelevant for ALLGUD purposes as you can't actually see inside the pouch while it's on your belt.

Could you install the patch and just double check that ti's not blatantly obvious that you're wearing septims while panning around your character in third person?  If it's not I'll go ahead and install the patch as is.

**Comment by LoD7995** [comment]
On your character it's practically impossible to notice. Only on other characters there's a chance, but you have to know where to look.

**Comment by jdsmith2816** [comment]
Done in next version
