### ISSUE TITLE
Regarding .ini files

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#169]
**SkyrimCustom.ini:**

[Display]

- fNearDistance=25.0000 - Causes you to glitch through objects when close up, even when playing with a relatively moderate fov of 75. Default is 15.00. I'm not sure why this has been changed in the first place, as lod flickering isn't as big as an issue in SE.

**Skyrim.ini:**

[Display]

- fGlobalContrastBoost=-0.1800 - This is a widely recommended .ini-change that does very little to improve the appearance of grass. If anything, it worsens the overall quality of the image. Changes like this are overridden by ENB anyway and have a negative impact on users that prefer to play without ENB.
- sScreenShotBaseName=F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Screenshots - A hint in the documentation to change the output folder would be appreciated, as not everyone has this specific setup.

**SkyrimPrefs.ini:**

[Display]

- bSAOEnable = 0 - A hint in the documentation for none ENB users to reenable this would be appreciated.

[Launcher]

- sD3DDevice = "NVIDIA GeForce GTX 1080 Ti" - Not sure if this has an actual impact on the game, but a hint in the documentation to change this to your personal graphics card would be appreciated once again.

**Comment by jdsmith2816** [comment]
```[Display]

fNearDistance=25.0000 - Causes you to glitch through objects when close up```

Gah! So that's what's causing it.  Thanks.

```ScreenShotBaseName=F:\SteamLibrary\steamapps\common\Skyrim Special Edition\Screenshots - A hint in the documentation to change the output folder would be appreciated, as not everyone has this specific setup.```

sD3DDevice = "NVIDIA GeForce GTX 1080 Ti" - Not sure if this has an actual impact on the game, but a hint in the documentation to change this to your personal graphics card would be appreciated once again.```

WJ is supposed to be blanking that out but apparently isn't... Should be a WJ bug report.  In either case I've removed them.

Corrected for next update.
