### ISSUE TITLE
Realistic Water Two aggravating an already existing issue

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#170]
Rain splashes get sometimes stuck in their animation. That goes for most movable statics in Enderal SE apparantly. The larger texture from RWT (fxsplash01sub.dds) makes this more obvious. Hiding/deleting it lessens the visibility.

Enclosed is a video demonstrating the issue.

https://user-images.githubusercontent.com/83468628/116736948-e1c59680-a9f0-11eb-8147-d75e6d0f03b5.mp4

**Comment by jdsmith2816** [comment]
Fixed next version.
