### ISSUE TITLE
Crashes involving Yuslan's, and his staff.

### ISSUE THREAD

**Issue by Asellia** [jdsmith2816/emw#173]
**Describe the bug**
Crashes whenever the model (I think? or the enchant effect, but I assume model) for Yuslan's Staff is seen. If you open his inventory and highlight it, or if he draws it for combat, the game will crash.

**To Reproduce**
Described above. It can occur during Drop in the Ocean anytime he goes to do combat (including entering abbey hall), or in The Shards of Order, Part 1. I assume any other time he attempts combat, too.

**Expected behavior**
That it wouldn't crash.

**Modlist version**
2.1.2

**Did you add any additional mods?**
Nope.

[Crash_2021_4_30_16-30-43.txt](https://github.com/jdsmith2816/emw/files/6408912/Crash_2021_4_30_16-30-43.txt)
[Crash_2021_4_30_19-38-46.txt](https://github.com/jdsmith2816/emw/files/6408913/Crash_2021_4_30_19-38-46.txt)

**Comment by jdsmith2816** [comment]
Fixed next version
