### ISSUE TITLE
Remove "Dave's HD Mountains 2K - Stonewalls"

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#176]
Textured aren't tailored to the mesh resulting in multiple seams.

Additionally, the original textures of the mod are more consistent with the mountain textures from Tamrielic Textures and the SlateRock.dds of the original mod (SLO - Stone Walls).

Dave's HD Mountains 2K - Stonewalls
![Skyrim Special Edition 30 04 2021 21_27_16](https://user-images.githubusercontent.com/83468628/116788504-3711ae80-aaaa-11eb-900d-c6164f4d1d33.png)

SLO - Stone Walls (Option 1)
![Skyrim Special Edition 01 05 2021 17_55_55](https://user-images.githubusercontent.com/83468628/116788509-41cc4380-aaaa-11eb-847b-9b03399e0bd1.png)

**Comment by jdsmith2816** [comment]
Agreed.
