### ISSUE TITLE
Add "Dog Replacer - Labrador"

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#177]
**Request**
To further diverge from Skyrim's fauna, I'd suggest this mod altough it might be somewhat of a subjective suggestion. 

Dark brown would possibly be the most beneficial colour variant, since black and white tend to be difficult with ENBs.

![maxresdefault](https://user-images.githubusercontent.com/83468628/116788938-a5577080-aaac-11eb-8201-255f0bd27928.jpg)

**Additional context**
https://www.mediafire.com/file/avxnxf3k37gtvy6/Labrador.7z/file

**Comment by jdsmith2816** [comment]
Great suggestion.

**Comment by jdsmith2816** [comment]
Done in next version
