### ISSUE TITLE
Refine selection of "Various Creatures Replacers"

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#178]
**Request**

Remove the following creatures:

Cave Troll - Meshes and textures are of very low resolution. I do like the design, but since this modlist is built around quality it doesn't really fit well.

Gnardalf - I think it is distracting to replace a creature with one from a different game (Witcher 3), even though the model might be appealing.

Wood Elemental - Same as above, but additionally, the matron hasn't been replaced so this specie is very inconsistent now.

**Additional context**

If there's interest, I could redo the plugin, but the meshes and textures would have to be disabled via the modlist.

**Comment by jdsmith2816** [comment]
Done in next version

**Comment by jdsmith2816** [comment]
Any news on the ice elemental replacer?  What assets were you using for that?

**Comment by LoD7995** [comment]
Was using the Ice Monarch model from "Artifacts - The Ice Blade of the Monarch"

https://www.nexusmods.com/skyrimspecialedition/mods/13972

There is no lootable model though and I don't have the skills to make one.

**Comment by jdsmith2816** [comment]
Done in v2.2.0
