### ISSUE TITLE
Remove Iced Aspens from "Rudy HQ - Enderal Mesh and Texture Fixes - Addons"

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#179]
Invisible iced aspens were fixed in 2.0.7, but "Rudy HQ - Enderal Mesh and Texture Fixes - Addons" is reverting them to their original state.

Meshes\enderal\landscape\trees:
treeaspeniced01.nif
...
treeaspeniced06.nif

**Comment by jdsmith2816** [comment]
Fixed.
