### ISSUE TITLE
Two handed blocking animation bugged

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#18]
**Describe the bug**
when blocking with a two handed weapon (with or without shield) since 1.0.2. the animation is bugged
**To Reproduce**
everytime reproducable

**Screenshots**

![20200525215949_1](https://user-images.githubusercontent.com/65853467/82841026-f0e4c000-9ed4-11ea-96cc-ef2579d42d72.jpg)
![20200525215955_1](https://user-images.githubusercontent.com/65853467/82841032-f4784700-9ed4-11ea-9d61-056be0bc3ce5.jpg)
![20200525220003_1](https://user-images.githubusercontent.com/65853467/82841035-f510dd80-9ed4-11ea-8afd-454d2430a47e.jpg)
![20200525220029_1](https://user-images.githubusercontent.com/65853467/82841038-f6420a80-9ed4-11ea-87a7-c97d95700bcf.jpg)
![20200525220037_1](https://user-images.githubusercontent.com/65853467/82841039-f6daa100-9ed4-11ea-946a-af3a08c1917a.jpg)
![20200525220044_1](https://user-images.githubusercontent.com/65853467/82841042-f80bce00-9ed4-11ea-94d5-3821c569193e.jpg)

**Modlist version**
1.0.2.

**Did you add any additional mods?**
nope

**Comment by jdsmith2816** [comment]
Fixed in 1.0.3
