### ISSUE TITLE
Parallax shader not working correctly on High Hrothgar meshes

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#180]
Parallax shader fix is enabled, "d3dcompiler_47.dll" is present in the game directory. Also checked for possible conflicts with BDS in xEdit but couldn't find any. 

Hiding/removing the meshes from "Skyrim Remastered - High Hrothgar" fixes it.

![Skyrim Special Edition 30 04 2021 22_23_38](https://user-images.githubusercontent.com/83468628/116794437-29215500-aacd-11eb-940e-3980550df746.png)

**Comment by LoD7995** [comment]
Shot was taken in the Apothecarii Monastery.

**Comment by jdsmith2816** [comment]
Fixed next version
