### ISSUE TITLE
Add "Real Rabbits HD - High Poly Mesh"

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#181]
**Request**
Only a slight increase in poly count, but a much smoother mesh.

Before
![rabbit nif - NifSkope 2 0 Dev 7 01 05 2021 22_58_32](https://user-images.githubusercontent.com/83468628/116794875-d0ec5200-aad0-11eb-9027-54cf9a313b77.png)

After
![rabbit nif - NifSkope 2 0 Dev 7 01 05 2021 22_55_33](https://user-images.githubusercontent.com/83468628/116794876-d21d7f00-aad0-11eb-982a-83daa1bb486d.png)

**Additional context**
https://www.nexusmods.com/skyrimspecialedition/mods/29223?tab=files
Under optionals.

**Comment by jdsmith2816** [comment]
Fixed in next version.
