### ISSUE TITLE
Nemsis detects multiple 32bit animations

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#182]
**Describe the bug**

Nemesis detects multiple 32bit animations. I'm not sure if this is of relevance, though, as I wasn't able to test these specific animations (since I don't know where exactly they are used).

WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture
File: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\_1stperson\animations\1hmlefthand_1stp_run.hkx

WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture
File: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\_1stperson\animations\dw_1stp_turnleft.hkx

WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture
File: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\_1stperson\animations\dw_1stp_turnright.hkx

WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture
File: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\_1stperson\animations\h2h_1stp_run.hkx

WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture
File: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\_1stperson\animations\h2h_1stp_walk.hkx

WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture
File: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\_1stperson\animations\h2h_equip.hkx

WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture
File: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\_1stperson\animations\h2h_idle.hkx

WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture
File: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\_1stperson\animations\h2h_unequip.hkx

WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture
File: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\animations\DynamicAnimationReplacer\_CustomConditions\70100\1hm_idle.hkx

WARNING(1027): 32bit hkx file detected. This file is not supported by current skyrim's architecture
File: c:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\data\meshes\actors\character\animations\DynamicAnimationReplacer\_CustomConditions\998\1hm_idle.hkx

**To Reproduce**
Simply rerun Nemesis.

**Comment by jdsmith2816** [comment]
This isn't a bug.
