### ISSUE TITLE
Add tent models and textures from "Langleys Textures Workshop"

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#184]
The models are fixing small UV issues, the textures are based of "PELTAPALOOZA - Pelts of Skyrim Expansion".

The files are present in the optional section named in a file named "Update".

https://www.nexusmods.com/skyrim/mods/26269?tab=files#

Models have to be converted most likely.

**Comment by jdsmith2816** [comment]
Fixed in next version.
