### ISSUE TITLE
Add "Forgotten Herbs"

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#187]
Great retexture of the herbs.

The model from "Skyrim 3D Trees and Plants" for Frost Mirriam would have to be removed though, otherwise the textures won't come into effect.

https://www.nexusmods.com/skyrim/mods/90755?tab=files

**Comment by jdsmith2816** [comment]
We're not actually using the frost mirriam from s3d plants.  I like this texture though so.. included in next update.
