### ISSUE TITLE
Replace "RUSTIC COOKING STATION" with "RUSTIC COOKING - Special Edition"

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#188]
**Request**
There are cheese and cabbage textures present in the SE version. Also, I would suggest letting "RUSTIC COOKING - Special Edition" overwrite "High Quality Food and Ingredients", except for the venisonmeatcooked.dds and the corresponding normal map.

https://www.nexusmods.com/skyrimspecialedition/mods/6142?tab=files

**Comment by jdsmith2816** [comment]
Done.
