### ISSUE TITLE
"True Wolves" inconsistency

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#190]
**Describe the bug**
"True Wolves" doesn't replace all wolves of Enderal yet.

meshes\enderal\actors\wolf\wolftimber.nif has to be replaced as well by simply copying and renaming wolfred.nif to said directory for example.

**Screenshots**

![Skyrim Special Edition 01 05 2021 21_27_43](https://user-images.githubusercontent.com/83468628/116823537-6517f100-ab85-11eb-8e08-f3860c6820ce.png)

**Comment by jdsmith2816** [comment]
Huh.  Thought I already did this... Awkward.  Fixed!
