### ISSUE TITLE
"Improved Atmosphere Mesh" actually worsens the horizon transition

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#191]
**Describe the bug**
By removing one horizon layer from the mesh, the transition becomes much more obvious.

With "Improved Atmosphere Mesh"

![Skyrim Special Edition 02 05 2021 01_21_04](https://user-images.githubusercontent.com/83468628/116823624-cb047880-ab85-11eb-8cec-943e95eaa5cf.png)

Without "Improved Atmosphere Mesh"

![Skyrim Special Edition 02 05 2021 16_34_31](https://user-images.githubusercontent.com/83468628/116823627-cc35a580-ab85-11eb-907e-6b80b352dc69.png)

**Comment by jdsmith2816** [comment]
Fixed in next version.
