### ISSUE TITLE
Rugs texture differences

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#193]
Certain rug meshes are differing, because SureAI made a texture set (TXST) change to some of them. Either fixable via .esp/.esl or via or copying the vanilla rug textures to the edited paths.

I'll upload a fix via .esp on discord, since github doesn't allow .7z files.

![SSEEdit 4 0 3 03 05 2021 00_40_19](https://user-images.githubusercontent.com/83468628/116923028-6533f180-ac56-11eb-9503-d8be9e8e362c.png)

**Comment by jdsmith2816** [comment]
Fixed in next version
