### ISSUE TITLE
Noble Skyrim texture issue

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#198]
**Describe the bug**
Noble Skyrim replaces some Windhelm ground textures with snow textures, which causes issues in certain areas (like the undercity).

The following textures need to be removed or replaced:

whroughground.dds
whroughground_n.dds
whstreetstone01.dds
whstreetstone01_m.dds
whstreetstone01_n.dds

**Comment by jdsmith2816** [comment]
Fixed in v2.2.0
