### ISSUE TITLE
Barrel texture issue

### ISSUE THREAD

**Issue by LoD7995** [jdsmith2816/emw#199]
**Describe the bug**
Enderal applies new texture sets to certain barrels, which causes issues with the new models that have a different UV layout.

Fixed .esp:
https://drive.google.com/file/d/1lhNtaz8RHmPsNj0YUEjCE4AdbIcJ7GJ0/view?usp=sharing

![Skyrim Special Edition 04 05 2021 19_33_36](https://user-images.githubusercontent.com/83468628/117138007-cb318d80-adaa-11eb-87b8-ecf1b1ff7406.png)

**Comment by jdsmith2816** [comment]
Fixed in v2.2.0
