### ISSUE TITLE
Create custom EAR and EWR alternative

### ISSUE THREAD

**Issue by jdsmith2816** [jdsmith2816/emw#20]
I'm really not a fan of the choices that the `Enderal Armor Replacer` and `Enderal Billyro Weapon Replacement` mods make.

Let's start by picking our own set of replacers for everything.  Once all of the wanted 'vanilla' enderal sets are done we can see about adding variety.

**Comment by NotTotal** [comment]
https://drive.google.com/open?id=1eVBIQwLiAhQ7mgqEkGXN-fm0hWLbbBWq female armor models in game
