### ISSUE TITLE
stretched 16:9 1080p on ultrawide monitors

### ISSUE THREAD

**Issue by rangda66** [jdsmith2816/emw#206]
**Describe the bug**
EMW running on 3440x1440 ultrawide borderless fullscreen runs in 16:9 1080p stretched.

The problem is caused by Display Tweaks - EMW Config "mod" under 01 ESSENTIAL MODS.  It has a SSEDisplayTweaks.ini ini file with the following:

Resolution=1920x1080
ResolutionScale=1.0

Unchecking this mod causes the game to come up in the correct resolution (I didn't try loading the game just observed the correct resolution at the title screen).

I haven't tested it yet but I'm assuming these two lines can probably be safely commented out of the ini file.

**To Reproduce**

1. Install emw per instructions
2. Check 2 21:9 mods in MO2
3. Run EMW

**Expected behavior**
Should run in 3440x1440.

**Did you add any additional mods?**

**Comment by rangda66** [comment]
Commented out Resolution/ResolutionScale in SSEDisplayTweaks.ini and the game comes up in the proper resolution.

**Comment by jdsmith2816** [comment]
Display Tweaks manages resolution; adjust it in there or comment it out as you said.
