### ISSUE TITLE
Weird colours for camps.

### ISSUE THREAD

**Issue by ganshunter** [jdsmith2816/emw#207]
**Describe the bug**
Rainbow mishmash colours for a camp;
**To Reproduce**
1. Go to the camp. Save.
2. Load the game the next day.

**Expected behavior**
Normal colours like brown? Isthis a bug?

**Screenshots**
![SkyrimSE 2021-05-22 18-17-43](https://user-images.githubusercontent.com/41804541/119235445-7d4ab280-bb2a-11eb-8a1c-e45d6c69ea05.png)

**Modlist version**
Latest, downloaded 2 days ago.
**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Fixed in next update
