### ISSUE TITLE
My character can't jump or use engarde dodge anymore.

### ISSUE THREAD

**Issue by Blamort** [jdsmith2816/emw#208]
After i change the bind of the LockOn mod my character simply can't jump and dodge (Engarde)  anymore, I tried to load older saves of the same character and the problem persist. I even tried to revert LockOn binds to default and nothing...

**Comment by rangda66** [comment]
I've just had this spontaneously happen.  While playing character cannot jump or use dodge.  Loading a previous save restores the functionality so whatever is doing it is sticky with saving.

**Comment by jdsmith2816** [comment]
This appears to be corrected in the latest build;  please respond with confirmation.

**Comment by rangda66** [comment]
Played 5-6 hours and haven't experienced the jumping/dodge bug.

**Comment by jdsmith2816** [comment]
Thanks for confirmation rangda!
