### ISSUE TITLE
Wabbajack list trying to download old version of mod that doesn't exist anymore.

### ISSUE THREAD

**Issue by IHateMakingUsernamez** [jdsmith2816/emw#227]
**Describe the bug**

Wabbajack can't finish downloading because the list calls for "DynDOLOD-Standalone.3.00-Alpha-35.7z"
and "xLODGen.83.7z"
Both of which are outdated versions of the current mod and the download pages have been pulled, so I cannot download them manually either.

**To Reproduce**

1. Go to 'Wabbajack app'
2. Do 'Try to Download and install the list'

**Expected behavior**

To finish downloading and installing the mods.

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

Direct quote from the app "Unable to download DynDOLOD-Standalone.3.00-Alpha-35.7z (MegaDownloader+State|https://mega.nz/file/tEh2AThZ#fJV4WkZ8Qaafcdbv8isdRnS4U7OfzqkTZhxm4_2TiEc)
17.19 - Unable to download xLODGen.83.7z (MegaDownloader+State|https://mega.nz/file/EcJhgKpY#4Q86Rd1hUepjm233r8Q_7x3fTWx9axJN2CUc8FXrBsg)
17.19 - Cannot continue, was unable to download one or more archives"

**Modlist version**
Current
**Did you add any additional mods?**
N/A

Wasn't sure if I should post this here or not but I wasn't sure if the wabbajack discord was the appropriate place either. Either way, hope the list can be updated or a solution found, as I'm very much looking forward to playing your mod picks!

**Comment by adam-ciszewski** [comment]
Same issue here. If you do not intend to keep the modlist up to date then please take it off Wabbajack gallery. Ended up downloading 60g for nothing.

**Comment by irischman** [comment]
The files are pinned on https://discord.gg/esGVnCjWpJ

https://cdn.discordapp.com/attachments/877326868095832175/912878351260217344/DynDOLOD-Standalone.3.00-Alpha-35.7z
https://cdn.discordapp.com/attachments/877326868095832175/912878313465339934/xLODGen.83.7z

**Comment by IHateMakingUsernamez** [comment]
Thanks man. I was looking everywhere for those files.
