### ISSUE TITLE
Weird texture issue in ARK

### ISSUE THREAD

**Issue by Naum31** [jdsmith2816/emw#24]
It happens in the Ark marketplace. See screenshot attached.
![20200525223219_1](https://user-images.githubusercontent.com/65632282/82863839-fe4f7980-9ed7-11ea-8c6f-9a625b93f211.jpg)

**Comment by jdsmith2816** [comment]
I'm unable to reproduce this.  Please try in 1.0.3 and re-open if it's still an issue.
