### ISSUE TITLE
Graphical bug, weird water textures

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#26]
**Describe the bug**
weird looking / missing water textures at Suncoast near Old Three River Watch

**Screenshots**
![20200526184146_1](https://user-images.githubusercontent.com/65853467/82928378-74101f80-9f82-11ea-86b0-bb3253a84119.jpg)
![20200526184145_1](https://user-images.githubusercontent.com/65853467/82928383-75414c80-9f82-11ea-8492-2bd6c35a022d.jpg)
![20200526184133_1](https://user-images.githubusercontent.com/65853467/82928388-76727980-9f82-11ea-83fd-7d9fe3af424a.jpg)
![20200526184127_1](https://user-images.githubusercontent.com/65853467/82928391-770b1000-9f82-11ea-88d5-5d2920792a97.jpg)

**Modlist version**
1.0.2
**Did you add any additional mods?**
nope

**Comment by jdsmith2816** [comment]
I'm unable to reproduce in 1.0.3;  if you still find this as a problem please re-open or file a new ticket.
