### ISSUE TITLE
Inconsistent perk "back" button language

### ISSUE THREAD

**Issue by Mofunkle** [jdsmith2816/emw#27]
The perk back buttons have inconsistent language. All the vanilla trees use the word "Back", whilst all the Forgotten Stories trees _mostly_ use "Return" instead with "Back" popping up every now and then. Strengthened Essence in the Lycanthrope tree uses "Zuruck."

Modlist v1.0.2

No additional mods

![20200526152551_1](https://user-images.githubusercontent.com/65977450/82942051-64cea900-9f65-11ea-968d-bc0001e69d74.jpg)
![20200526152603_1](https://user-images.githubusercontent.com/65977450/82942054-65673f80-9f65-11ea-8930-b8e4ee724432.jpg)
![20200526152630_1](https://user-images.githubusercontent.com/65977450/82942056-65673f80-9f65-11ea-82a3-96739a8dfe78.jpg)
![20200526152642_1](https://user-images.githubusercontent.com/65977450/82942059-65673f80-9f65-11ea-83ce-7e4fcd4562e0.jpg)

**Comment by jdsmith2816** [comment]
Fixed in 1.0.3
