### ISSUE TITLE
Balance issue: Soul gem and Potion combiner in Marketplace House mod

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#28]
both of these items let you create maxed items - soul gems, filled soul gems ... maxxed health, mana and stamina potions. 

Too OP, IMO

**Comment by jdsmith2816** [comment]
Agreed.  This will be chopped.

**Comment by jdsmith2816** [comment]
Maybe fixed in 1.0.3?  The mod recently updated to have skill requirements for these.  Re-open this if it still feels wrong.
