### ISSUE TITLE
Minor graphical bug: Floating grass

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#30]
**Describe the bug**
Floating grass textures in "Grotto at the Crossroads" near Ark

**Screenshots**
![20200528223712_1](https://user-images.githubusercontent.com/65853467/83192043-47e8d000-a135-11ea-844d-255f0e0fcd09.jpg)

**Modlist version**
1.0.2
**Did you add any additional mods?**
nope

**Comment by jdsmith2816** [comment]
Fixed in 1.0.3
