### ISSUE TITLE
AllGUD not functioning with certain races

### ISSUE THREAD

**Issue by Mofunkle** [jdsmith2816/emw#31]
**Describe the bug**
Weapons don't appear on the back of both the Half Qyranian and Half Arazealean races unless currently equipped. Staves don't appear on back at all.

**To Reproduce**
1. use showracemenu console command to switch to either of the above-mentioned races.

**Expected behavior**
I expect to be able to see favorited weapons on back.

**Screenshots**
![20200528165550_1](https://user-images.githubusercontent.com/65977450/83192880-23c0cb00-a104-11ea-82f6-11977ff65d20.jpg)

**Modlist version**
v1.0.2

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Fixed in 1.0.3
