### ISSUE TITLE
Error during install - "Unable to download Animation Package_2.0.rar"

### ISSUE THREAD

**Issue by buddhokage** [jdsmith2816/emw#32]
**Describe the bug**
While using the Wabbajack installer, it runs for a certain time and eventually ends with the error in the title.

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/15185163/83212295-16134180-a114-11ea-97fd-7b375e3aa2ed.png)

**Modlist version**

**Did you add any additional mods?**

**Comment by jdsmith2816** [comment]
Download the file manually at the link below and place it into your downloads folder before restarting the installation procedure.  Also consider joining our discord server and asking these questions in #enderal-my-way-support

http://www.mediafire.com/file/4cgr1yeem36rkb9/Animation_Package_2.0.rar/file

**Comment by buddhokage** [comment]
Thank you. That fixed the install but I'm having another issue when I run the game now. Are you referring to the Wabbajack Discord or do you have a different one?
