### ISSUE TITLE
Wolf Blood and Chymicum not spawning

### ISSUE THREAD

**Issue by Mofunkle** [jdsmith2816/emw#33]
**Describe the bug**
Wolf Blood and Chymicum won't spawn in the player inventory after crafting either potion. You get notified in the top left of your window that the potion was created successfully and added to your inventory, but when you go to check, it isn't there. Seems to be related to the SKSE version in EMW, as unticking SKSE in the left pane of MO2 fixes the problem.

**To Reproduce**

Attempt to craft either a wolf blood or chymicum potion. You can use wolf claws and red malphas flowers to make wolf blood. You can give yourself the "Portable Laboratory" perk if you don't feel like running to find an alchemy bench.

**Expected behavior**
I expect Wolf Blood and Chymicum to go to my inventory after crafting it.

**Screenshots**
![20200529232328_1](https://user-images.githubusercontent.com/65977450/83318506-a2e8f880-a203-11ea-95e1-7eb5f3123ce5.jpg)
![20200529232335_1](https://user-images.githubusercontent.com/65977450/83318508-a8464300-a203-11ea-93eb-69468a08f32f.jpg)
![20200529232408_1](https://user-images.githubusercontent.com/65977450/83318511-ac726080-a203-11ea-9676-16037485d950.jpg)

**Modlist version**
v1.0.2

**Did you add any additional mods?**
No.

**Comment by jdsmith2816** [comment]
Fixed in 1.0.3
