### ISSUE TITLE
Balancing: 'Black Mage' set from katapump spell package

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#34]
**Describe the bug**
The craftable 'Black Mage' set is to easily crafted. You only need 30 in smithing, cheap materials and no blueprints. 

**Screenshots**
![20200530221857_1](https://user-images.githubusercontent.com/65853467/83338472-1141bf80-a2c5-11ea-92f5-299b2e1a5f7c.jpg)
![20200530221904_1](https://user-images.githubusercontent.com/65853467/83338473-1272ec80-a2c5-11ea-8de2-fd5328a621f9.jpg)
![20200530221906_1](https://user-images.githubusercontent.com/65853467/83338475-130b8300-a2c5-11ea-8cd7-1999123e2765.jpg)
![20200530221908_1](https://user-images.githubusercontent.com/65853467/83338476-143cb000-a2c5-11ea-8b7a-8448134bbecb.jpg)

**Modlist version**
1.0.2.
**Did you add any additional mods?**
no

**Comment by jdsmith2816** [comment]
These were never supposed to be in the game... They've been removed in 1.0.3
