### ISSUE TITLE
Starling and Order of the Righteous Path SHield have the same Armor rating

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#35]
Starling SHield either needs to go down, or OotRP shield needs to go up

**Comment by jdsmith2816** [comment]
Hmm... Shield of the Righteous Path has 32 armor and Starling has 15. I'm not sure what you're seeing

**Comment by Lazasar** [comment]
![image](https://user-images.githubusercontent.com/18401877/83862711-ff2fa900-a72a-11ea-8002-747a993ac08a.png)
![image](https://user-images.githubusercontent.com/18401877/83862757-0eaef200-a72b-11ea-9db1-9d51628633bf.png)
