### ISSUE TITLE
Quick Loot and Marketplace house cause CTD

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#36]
This isn't 100% reproducible, but it seems that Quickloot causes a CTD on occasion when looking at some of the containers in the player house mod in the marketplace

**Comment by jdsmith2816** [comment]
I've disabled QuickLoot by default in 1.0.4 as it breaks a few features of Enderal like the dig spots.  both crashes I've experienced in the past 20h have also related to QuickLoot I think.

The mod is now disabled by default but still included so those that want to keep using it can.
