### ISSUE TITLE
Unable to download RGE Random xEdit Scripts.zip

### ISSUE THREAD

**Issue by Mortulak** [jdsmith2816/emw#43]
**Describe the bug**
Unable to download RGE Random xEdit Scripts.zip, deleting the file in downloads and starting Wabbajack again doen't fix it. File appears again in download but installtion doesn't continue

**To Reproduce**
Install latest release from Disk

**Expected behavior**
Finishing downloads and start Installation

**Screenshots**
![image](https://user-images.githubusercontent.com/66409946/83730223-0d0cfd80-a649-11ea-830e-19bbf20e4def.png)

**Modlist version**
1.03

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Check the pins in #enderal-my-way-support on the WJ discord for the file you need... Place it in your downloads folder and the install will complete.  This is fixed for the upcoming 1.0.4 release
