### ISSUE TITLE
Armor set fix needed

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#44]
**Describe the bug**
torso doesn't match with leg

![20200605000944_1](https://user-images.githubusercontent.com/65853467/83816318-6b29f700-a6c2-11ea-8866-4c7fdc0eb2b5.jpg)

**Modlist version**
1.0.3
**Did you add any additional mods?**
no

**Comment by jdsmith2816** [comment]
Fixed for 1.0.4
