### ISSUE TITLE
-Hitbox Issue with Trolls in the quest Wanted in Riverville! 

### ISSUE THREAD

**Issue by AFranklin41** [jdsmith2816/emw#45]
**Describe the bug**
Trolls are still too big, a bunch of the trolls in this quest can't navigate the cave they're placed in and are completely stuck.

**To Reproduce**

1. Go to Shimmering Cove (coc shimmeringcove) on the quest Wanted in Riverville! after you have successfully cleared the first stage (Receive Redrick Borecut's Bounty)
2. Observe Trolls that cannot move

**Expected behavior**
The trolls should probably be able to move

**Modlist version**
1.0.3

**Did you add any additional mods?**
No

**Comment by jdsmith2816** [comment]
Thanks, I'll shrink the trolls a bit more and re-test using that specific cave.

**Comment by jdsmith2816** [comment]
@AFranklin41 could I convince you to test this on a vanilla Enderal profile and let me know if the problem still persists?  I scaled the troll race down by 10% and shrunk their bounding box and collider capsules but the problem still persists.  I also shrank them to a ridiculous size in game... same problem.  I wonder if this is vanilla Enderal behavior?  If you're unable to perform a test by the time I release later today/tomorrow then I'll take care of it in the next update.. My in-game time is really limited right now.

**Comment by AFranklin41** [comment]
I went in with a vanilla profile and it definitely doesn't seem to occur without mods. The trolls are moving around naturally through the cave and I'm not seeing any issues where they are getting stuck with the exception of a thin tunnel in the middle of the cave.

In my modded profile the trolls were clipping so bad they actually weren't capable of moving from their spawn points. 


[Here's a screenshot of their model size in vanilla, not sure if this is helpful](https://i.imgur.com/J5btGBE.jpg)

**Comment by jdsmith2816** [comment]
Thanks for looking into that franklin.  I'll do some more digging next time I'm updating EMW.
