### ISSUE TITLE
Ratcatcher gloves are transparent on the seam with torso armor

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#5]
**Describe the bug**
See attachment

**Did you add any additional mods?**
![image](https://user-images.githubusercontent.com/18401877/82442680-cb0c8500-9aa8-11ea-802d-866c15cd4a49.png)

**Comment by Kosake77** [comment]
It is because of the mod [https://www.nexusmods.com/enderal/mods/12](url) Enderal Armor Replacer. If you have the full Ratcatcher set equipped it looks fine. Those gloves just don't fit together with any other torso armor.

**Comment by jdsmith2816** [comment]
Thanks.  I'm kind of working on my own version of EAR that wlil just be for this modlist...  The problem will resolve itself by the time I'm done.  Going to close this as progress on the EAR replacer can be tracked separately.
