### ISSUE TITLE
Fighting the "Monster" in the Dust Pit buggy/broken

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#50]
**Describe the bug**
5. fight during the "Blood and Dust" quest in the dust pit.
You will fight the "Monster". At the start the commentator makes a speech like always. During that speech you can't move until the fight actually starts. The monster is in a cage. At the end of the speech the cage gets opend by an NPC and the monster should come out and the fight should start. But the beast just glitches in and out of the cage. I tried decreasing its size with setscale hoping that that would improve things, but it doesn't help. Essentially you are now stuck and can't move (cause the fight didn't actually start) and have to reload a previous save. Completing that questline unlocks a big side quest, so solving that issue might be important. 
I uploaded some screenshots and a save just before the fight ( talk with Rasha infront of you to start the fight)
Edit: "moveto player" solved it for me

**Screenshots**
![20200606185849_1](https://user-images.githubusercontent.com/65853467/83950461-3ab19c80-a82b-11ea-9eb6-317709509168.jpg)
![20200606185806_1](https://user-images.githubusercontent.com/65853467/83950467-44d39b00-a82b-11ea-9e4b-7b9df96b8683.jpg)
![20200606185656_1](https://user-images.githubusercontent.com/65853467/83950468-4604c800-a82b-11ea-9298-3c88c8364345.jpg)
![20200606185649_1](https://user-images.githubusercontent.com/65853467/83950469-469d5e80-a82b-11ea-8bac-cf7b24ca664e.jpg)
![20200606185610_1](https://user-images.githubusercontent.com/65853467/83950471-47ce8b80-a82b-11ea-86fb-da88611a3c54.jpg)

save:
[save.zip](https://github.com/jdsmith2816/emw/files/4740672/save.zip)

**Modlist version**
1.0.3
**Did you add any additional mods?**
no

**Comment by jdsmith2816** [comment]
Thanks, I'll make sure this gets fixed for the next real update.

**Comment by jdsmith2816** [comment]
This is no longer an issue for the upcoming release.
