### ISSUE TITLE
Suggestion: Balancing: Remove Fire/Frost/Shockshield spells introduced by Katapumb

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#52]
**Request**
In general increasing magic resist can be accomplished using three different methods: 

1. Potions
2. .Enchantments
3. Mentalism spells/perks

From a balancing and gameplay perspective the player should be forced to use at least two combat or crafting skills to achieve 100% magic resist. f.e. a potion that grants 100% magic resist can be considered op.

While leveling Mentalism the player already gets 20% resist from perks in the Thaumaturge tree. Additionaly the "Protection from Magic" spell grants (with all perks from the Thaumturge tree) 42% magic resist on its highest level.
Katapumb introduced with Frost-/Fire-/ and Shockshield new low mana cost magic resistance spells that only increase the resist against one element. Still nothing prevents the player from casting all three spells. With all perks those shield spells grant ~~25%~~ 63% magic resist.

In total you end up with ~~87%~~  125% magic resist while leveling/using only one combat skill, which is way to high imo.

**Comment by jdsmith2816** [comment]
This is well reasoned. I will make adjustments in the next real update.

**Comment by jdsmith2816** [comment]
Before just flat out removing them let's try nerfing.  For now i've halved the magnitude of all ranks for each of the three spells.

**Comment by jdsmith2816** [comment]
If after playing with the new update for a while this still feels really unbalanced please re-open/make a new ticket and we'll adjust further or remove.
