### ISSUE TITLE
Not possible to improve male versions of set helmets on work benches.

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#53]
**Describe the bug**
I recently got the perk "Arcane Smith" which allows improvement of enchanted equipment. 
However male versions of head gear can't be improved. 
They also can't be crafted backwards into female versions.
Female variants can be improved. However if you convert them into male versions, they are back to vanilla stats.

**Modlist version**
1.0.3
**Did you add any additional mods?**
no

**Comment by jdsmith2816** [comment]
Ah, the temper recipes for these were probably missed. Thanks, will fix.

**Comment by jdsmith2816** [comment]
This is no longer an issue for the upcoming release.
