### ISSUE TITLE
Effects of "Blessing of Life" tier 2 and 3 mixed up

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#54]
**Describe the bug**
Effects of "Blessing of Life" tier 2 and 3 mixed up. 
tier 3 costs more mana (as it should) but has a weaker effect (lower duration, lesser health) as tier 2.

**Screenshots**
![20200609192720_1](https://user-images.githubusercontent.com/65853467/84181286-fae7f080-aa88-11ea-9b5f-144b0cd1644d.jpg)
![20200609192723_1](https://user-images.githubusercontent.com/65853467/84181290-fc191d80-aa88-11ea-9e8b-a0d186c592bd.jpg)

**Modlist version**
1.0.3
**Did you add any additional mods?**
no

**Comment by jdsmith2816** [comment]
Fixed in 1.0.5
