### ISSUE TITLE
Ultimate Combat seems to break the stagger system

### ISSUE THREAD

**Issue by Mofunkle** [jdsmith2816/emw#56]
**Describe the bug**
With Ultimate Combat it seems like the poise system is active regardless as long as you have the mod active. The "enemy poise" option seems to only affect whether or not NPCs have **resistance** to being staggered. With it unchecked, you can stagger someone with a bow, with no perks, almost indefinitely. If you in turn check the enemy poise option, the inverse occurs to where you stagger people very rarely, after hitting them enough times. After giving myself the "Master Thief" perk with the console (the one that allows you to frequently stagger people with bows), it had no affect on my ability to stagger people. With this, I assume that UC's poise system is overwriting Enderal's entire stagger mechanic. You'll probably be able to find a more intuitive fix than whatever comes off the top of my head, but it might be easiest to just roll UC back to a version prior to 3.0, when the poise system was implemented.

**To Reproduce**

1. Equip a bow.
2. Find an enemy (or friend if you're feeling lazy/mean).
3. Spam them arrows.

4. Repeat as necessary with the enemy poise option checked/unchecked to see the difference.
5. Give yourself the Master Thief perk and repeat again.

**Expected behavior**
I expect to be unable to stagger most targets with a bow _without_ having the Master Thief perk, and I except to be able to stagger most targets _with_ the Master Thief perk.

**Modlist version**
v1.0.4
**Did you add any additional mods?**
Run Sprint and Jump (replacing Realistic Animation Project - Movement)
https://www.nexusmods.com/skyrim/mods/34960

**Comment by jdsmith2816** [comment]
Shit.  That's no good.  Thanks.

**Comment by jdsmith2816** [comment]
This is fixed by setting Player Bow Poise and NPC Bow Poise to 0.0 int he UC MCM.
