### ISSUE TITLE
Replace "Realistic Animation Project - Movement" with "Run Sprint and Jump"

### ISSUE THREAD

**Issue by Mofunkle** [jdsmith2816/emw#57]
**Request**
In case anyone else thinks RAP-M looks a bit wonky (run anim looks off-balance and people generally don't karate chop through the air when going for a light jog) I'd like to suggest Run Sprint and Jump (https://www.nexusmods.com/skyrim/mods/34960) as an alternative. It has a much more relaxed and natural running animation (subtle forward lean and minimal arm pumping). I could take or leave the sprint animation from either mods, but I do think the jump animation is superior in RAP-M, so maybe there's a way to merge the two.

Either way, it's super easy to just replace RAP with RSJ and just rerun nemesis after each modlist update, so I'm just suggesting this in case you guys aren't satisfied with the animations yet.

**Comment by jdsmith2816** [comment]
I'll make this change in the next real update.

**Comment by jdsmith2816** [comment]
Fixed in 1.0.5
