### ISSUE TITLE
Arcanist's Backpack: wrong carry capacity

### ISSUE THREAD

**Issue by Kosake77** [jdsmith2816/emw#58]
**Describe the bug**
Description: 80 carry capacity increase
when equipped: 55 carry capacity increase

I think 80 should be right here since you need 75 handicraft to craft just like the Vagabond's Sack which also has an increase of 80 carry capacity.

**Screenshots**
![20200612231315_1](https://user-images.githubusercontent.com/65853467/84547555-1874be80-ad04-11ea-8a6f-a1774f25998d.jpg)
![20200612231318_1](https://user-images.githubusercontent.com/65853467/84547557-19a5eb80-ad04-11ea-9c42-a8f068561845.jpg)

**Modlist version**
1.0.3
**Did you add any additional mods?**
no

**Comment by jdsmith2816** [comment]
Fixed in 1.0.5

Changed carry weight to 80 and updated the description to reflect that the mana boost is really 25
