### ISSUE TITLE
Highwayman doesn't attack

### ISSUE THREAD

**Issue by Lazasar** [jdsmith2816/emw#6]
**Describe the bug**
Most human NPCs attack just fine, but there seems to be one kind that doesn't. he has a shield armed, but no weapon wielded (even tho he has one in his inventory), and he doesn't attack... he just lets me beat him up.

![image](https://user-images.githubusercontent.com/18401877/82479305-dd071b80-9ada-11ea-9110-d64cfc158b75.png)

**Comment by jdsmith2816** [comment]
This appears to be fixed in 1.0.1 via the CGO update.  Please re-open if you can still reproduce.
