### ISSUE TITLE
ALl Geard Up Meshes and nodes?

### ISSUE THREAD

**Issue by RelicLTD** [jdsmith2816/emw#62]
**Describe the bug**
Meshes didnt work properly. When returning the replaced Iron Shield, the regular skyrim iron shield appeared on my back.

IM also unable to assign new locaitons or force weapons to stay on character in the All geard up MCM menu

**To Reproduce**
- Install mod. Obtain Iron shield. Enable ALl geard up. Equip and favorite. equip new item in left hand but leave shield favorited.

**Expected behavior**
Modded mesh of new iron shield to appear on back.

**Screenshots**
- 
![image](https://user-images.githubusercontent.com/25216390/90290236-58564000-de32-11ea-9c2a-593cec6e8db8.png)

**Modlist version**
1.0.7
**Did you add any additional mods?**
No

Resolved by running AGU patcher.

**Comment by birbrunner** [comment]
i'm having this same issue with every vanilla shield and weapon that is supposed to be replaced with a new mesh.

**Comment by RelicLTD** [comment]
@birbrunner I was able to resolve the shields and weapons issue by making sure I was running the all geared up patcher in the mods/tools folder. I still couldn't change node locaitons, but im not really sure what normal functionality is supposed to be for that as I haven't played skyrim in many years.

**Comment by jdsmith2816** [comment]
Regenerated all ALLGUD meshes in 1.10; this should be fixed now.  Please let me know if you have further problems after installing the update once it releases.
