### ISSUE TITLE
Please add "Wildcat" (just Injuries-mechanics)

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#63]
Have been testing it intensely. It's working without problem.

Just activate injuries options with burst damage stagger (all other mechanics have to be disabled).

Plus set the stamina costs to zero so that intended values are calculated.

Also the attached patch for Enderal is needed.

Wildcat must be loaded before all other combat mods (and respectively EGO)

Thesr infos needs to be mentioned in guide's MCM configuration section.

Kind regards 😉

**Comment by jdsmith2816** [comment]
I'll pass.
