### ISSUE TITLE
Arcanist blueprints (robes, gauntlets, boots)

### ISSUE THREAD

**Issue by Palpou** [jdsmith2816/emw#68]
Hello,
I have purchased Arcanist Blueprints but in my house in the marketplace I cannot craft them. I am level 21 for crafting so it should be right (>= 20).
I don't have Arcanist gauntlets nor boots under armors if I try to type "help" in the console menu.
It seems it is not in the (official ?) list of blueprints for equipments: https://en.wiki.sureai.net/Enderal:Blueprints

Here are pictures with the items (I let them in the house, but I'm in a shop at the moment that has these items), and the ID :
![20200909230445_1](https://user-images.githubusercontent.com/19576421/92655024-0699bc00-f2f1-11ea-8c07-f68c376e5133.jpg)
![20200909230317_1](https://user-images.githubusercontent.com/19576421/92655029-08637f80-f2f1-11ea-8fec-987e8633b96f.jpg)

Thank you for your amazing work compiling all these mods, it has been a long time I didn't actually play games because modding take a lot of time...

Edit : same thing with blueprints for **spell tomes**. For exemple I have a blueprint with ID 2500A5F5 for "Blueprint: Spell Tome (Psionics)" but I don't know where and how to craft it, and cannot give me the item because it does not exist.. !

**Comment by jdsmith2816** [comment]
Ah, sorry yes the blueprints from katapumb spellpackage should not exist.  This is fixed in 1.0.10 thanks!
