### ISSUE TITLE
"Lb" sprint won't work (PC controller xbox)

### ISSUE THREAD

**Issue by Palpou** [jdsmith2816/emw#69]
Hello there,
When I'm using the keyboard, I can run (shift key), I can always run or walk (maj cap key), or I can sprint (left alt).
But when I'm using the controller (xbox one for PC), the left bumper (Lb) won't work for sprinting. It works with Skyrim and I believe it worked before installing My Way.
Loading old saves or starting a new game won't solve the problem.
Resetting every shortcut by default don't work. Changing the shortcut for another one doesn't work either. Trying another mod that change controller configuration doesn't work either.
It miraculously works only if I'm in the third person camera, and if I'm drawing or sheathing a weapon or a spell while pressing Lb. Once it works, I can go back in first person point of view if and only if I'm still pressing Lb.

Thank you.

**Comment by jdsmith2816** [comment]
Should be working in 1.0.11
