### ISSUE TITLE
Rodas - pale Skin, toned body

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#70]
![72850_20200914192953_1](https://user-images.githubusercontent.com/69637298/93118979-5b5a7f80-f6c1-11ea-8758-a8df494afb4a.png)

**Comment by kratores85** [comment]
![original](https://user-images.githubusercontent.com/69637298/93119187-a70d2900-f6c1-11ea-96f5-a1c0bf49e568.jpg)
Original

**Comment by kratores85** [comment]
![72850_20200916081358_1](https://user-images.githubusercontent.com/69637298/93305581-fb69f300-f7fe-11ea-9b3c-64338dabdf08.png)
Here you go 👍

**Comment by jdsmith2816** [comment]
This is no longer an issue for the upcoming release.
