### ISSUE TITLE
Please add "GIST - Genuinely Intelligent Soul Trap with Multilayer Parallax Soul Gems patch"

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#72]
It's working without problems in Enderal. It's such a quality of life optimization. No longer you need to take care, which soul you trap.. They're fitted (multithreading) into existing empty soul gems and re-assigned if you find e.g. a smaller or larger - vice versa.

**Comment by jdsmith2816** [comment]
Fixed in upcoming v1.0.11 update
