### ISSUE TITLE
Reduce Mana Cost for "Send Items Home" Spell (House at the Marketplace - Redone)

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#74]
In my case the spell costs 186 Mana, so that's way too much (especially for a non-mage build)
![image](https://user-images.githubusercontent.com/69637298/93323686-3aa33e80-f815-11ea-960b-da94579fc997.png)

I set it to 25 - so in-game it costs 54 instead of 186.

Thank you in advance :)

**Comment by jdsmith2816** [comment]
Has already been fixed by removal of the spell... A previous update made it not spawn in the chest.  You probably already had created your character and discovered the spell before that change happened.
