### ISSUE TITLE
Fix broken installer (v1.0.10)

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#75]
![image](https://user-images.githubusercontent.com/69637298/93336907-aba02180-f828-11ea-9d8f-7f77d4a517b4.png)
Thank you 👍

**Comment by kratores85** [comment]
This one is fixed now.. but there's a Problem with CC's Enhanced Ore Veins SSE Edition
https://www.nexusmods.com/skyrimspecialedition/mods/1306?tab=files
![image](https://user-images.githubusercontent.com/69637298/93425742-e6529a00-f8ba-11ea-98f0-8799a3d46d0c.png)

**Comment by jdsmith2816** [comment]
Fixed in v1.0.11
