### ISSUE TITLE
whenever i try to use a set of armor from practical armors it doesn't show as leather armor aswell as servel individual pieces of armor not showing like selna's veil i did not add any new mods i'm using the exact version from wabbajack  

### ISSUE THREAD

**Issue by Kadzter** [jdsmith2816/emw#76]
**Describe the bug**

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**

**Comment by kratores85** [comment]
regarding Selna's veil I can confirm the clipping issue. But every piece is showing on my side.. @Kadzter Can you post a screenshot, please? Helmet's are hidden by default..
![72850_20200916154830_1](https://user-images.githubusercontent.com/69637298/93346849-b52f8680-f834-11ea-8326-135ea27c8bc0.png)

**Comment by Kadzter** [comment]
![72850_20200916132332_1](https://user-images.githubusercontent.com/71389531/93371198-f7020200-f81f-11ea-9657-06f34d4ab3e6.png)
![72850_20200916132336_1](https://user-images.githubusercontent.com/71389531/93371208-fa958900-f81f-11ea-832a-03dbedbd64f8.png)

**Comment by Kadzter** [comment]
my selna's armor looks different
