### ISSUE TITLE
Why was Detect Dead remove ? + remove Disenchanted from description

### ISSUE THREAD

**Issue by Palpou** [jdsmith2816/emw#78]
Hello.
1) Why did you remove Detect Dead ? (sorry I can't find why in the issues)
2) If you removed the mod Disenchanted (which worked as intended for me), you should remove it from your description list : https://github.com/jdsmith2816/emw#updating
Thanks.

**Comment by jdsmith2816** [comment]
1. Detect Dead is now handled via the base game or EGO i forget which
2. It was removed due to general low quality.  I'll update the readme.
