### ISSUE TITLE
Enhanced Ore Veins - unable to download

### ISSUE THREAD

**Issue by Palpou** [jdsmith2816/emw#79]
Hi,
I can't update Enderal My Way because of Enhanced Ore Veins.
I can't do a fresh install either.
Thanks.

![Bug](https://user-images.githubusercontent.com/19576421/93711093-abb36080-fb4b-11ea-9b24-ec64c97fc7d4.jpg)

----------------------
Edit : Does not work with the release tab, nor by running Wabbajack and selecting Browse Modlists.
----------------------
Edit 2 : sorry just read the thread, I'm going to place the file manually in the download section.

**Comment by Palpou** [comment]
You can close my issue, I downloaded it manually. But there is a problem with the automatic installation.

**Comment by fibrils** [comment]
I have the same issue but placing the file manually doesn't change anything for me.

**Comment by fibrils** [comment]
I have the same issue and placing manually to download section doesn't fix automatic install.

**Comment by Martneb** [comment]
For me too, pls fix this as soon as you can Thanks

**Comment by kvarga74** [comment]
Noticing that this error has been around for a while now and the modlist appears to be not downloadable for over a month?
Shouldn't it be taken down from Wabbajack?

**Comment by jdsmith2816** [comment]
I've been unavailable... an update will happen soon.  Having said that the last I heard if you grab the SE version of enhanced ore and place it manually in the downloads folder then the install will complete.

**Comment by Martneb** [comment]
tried that one, still puts out an error

**Comment by Palpou** [comment]
I don't remember everything I did, but I read the instructions of the modpack, downloaded the mod on nexus, and that's how it worked for me (just followed the instruction).

**Comment by jdsmith2816** [comment]
Fixed in 1.0.11
