### ISSUE TITLE
Compass missing

### ISSUE THREAD

**Issue by SatyrTheDemon** [jdsmith2816/emw#8]
Like the title says, the compass is missing, I tried to look into immersive hud and the other hud mods but didn't find a way to put it back, also installed a minimap mod but it doesn't show. Any idea why these HUD elements are hidden?

**Comment by Lazasar** [comment]
Just need to go into enderalprefes.ini and change bShowCompass=0 to 1

**Comment by jdsmith2816** [comment]
This is fixed in 1.0.2
