### ISSUE TITLE
Cream Pie has the model of a Roll (Skyrim 3D Cooking)

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#80]
Still consists in EMW 2.1.2

![Rule-Creampie](https://user-images.githubusercontent.com/69637298/115381724-23299b00-a1d4-11eb-929d-02415dca89da.jpg)

It should be a creampie and not a roll - also stats-based it's giving you an endurance buff - which means it contains sugar heheh :)

**Comment by kratores85** [comment]
![image](https://user-images.githubusercontent.com/69637298/93742817-15d11180-fbef-11ea-9ae0-b2670dce0311.png)
Renamed it on my side to "Roll" / "Semmel" (German)

**Comment by kratores85** [comment]
Texture should be a creampie, but I like it better to be a Roll / Semmel, since there is Endralean Bread and Pretzel's, too.

**Comment by kratores85** [comment]
If using the one from Forgotten Retex Project then it's the big version of Creampie and that's also fitting with the values (Stamina), since cakes/pies also boosts stamina regen, roll wouldn't fit anyways since it's like a Bread that just boost HP-regen.
![image](https://user-images.githubusercontent.com/69637298/93745170-5e8ac980-fbf3-11ea-9e09-ef13286f4369.png)
![72850_20200921101433_1](https://user-images.githubusercontent.com/69637298/93745381-bf1a0680-fbf3-11ea-836b-4c24ec360f55.png)

**Comment by kratores85** [comment]
Better using the vanilla one, since this one is too big and gives lower boost-values than normal cakes. So would suggest to set file name of 3D Cooking's Butcherscotch Cream Pie to mohidden, too.
![image](https://user-images.githubusercontent.com/69637298/93745821-7020a100-fbf4-11ea-9a56-869108ee4779.png)

**Comment by kratores85** [comment]
Problem still consists in EMW 2.0
![SkyrimSE 2021-03-03 16-21-46](https://user-images.githubusercontent.com/69637298/109828088-9c792880-7c3c-11eb-90f1-2885940419ec.png)

**Comment by kratores85** [comment]
![Rule-Creampie](https://user-images.githubusercontent.com/69637298/115381724-23299b00-a1d4-11eb-929d-02415dca89da.jpg)
Since in Enderal there's Bread (Endralean Bread) the Rule-model would perfectly fit to the bakery.. but it's sadly shown as a creampie..

**Comment by kratores85** [comment]
![image](https://user-images.githubusercontent.com/69637298/115383924-afd55880-a1d6-11eb-9bbe-b467aefff880.png)

**Comment by jdsmith2816** [comment]
Fixed in next update.
