### ISSUE TITLE
Graphical Glitch: Colored vertical (high)lighting (random) / ENB fade-out?

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#83]
Does these red/orange/yellow mixed vertical (high)lighting in distance occur on your side, too? It's very random and seems to be connected to the randomly black fade-out from Rudy's ENB (general ENB issue as I read on some posts)..

Couldn't fetch a screenshot yet..

**Comment by jdsmith2816** [comment]
Unable to reproduce
