### ISSUE TITLE
Secure chest disappeared after update

### ISSUE THREAD

**Issue by Palpou** [jdsmith2816/emw#84]
Hi, it seems every secure chest disappeared in towns and near towers since I updated to the .10 udpate for My Way.
There is only one secure chest in my market home in Ark.
Luckily I moved everything in my inventory before updating.
I tried exiting/launching the game three times ; I tried very old saves from the begining of my character, but chests are gone.

Thanks.

--------------------
Edit : A possible solution I will use for now is the console to manually place some secure chests ("player.placeatme 2EDD7")
Edit 2 : Nevermind, it seems the secure chests removed were part of the mod EGO - Enderal Gameplay Overhaul. It's not a new mod in My Way, but somehow I still had chests until now. I will play without them if it's intended and if it's not a bug.

**Comment by jdsmith2816** [comment]
Not a bug;  the changelog specifically mentioned this.
