### ISSUE TITLE
Wabbajack Installation fail

### ISSUE THREAD

**Issue by MaiqTheLiarr** [jdsmith2816/emw#86]
Description:
Everytime I try to install this modlist Wabbajack gives me this response. The installation fails every time

![Screenshot (17)](https://user-images.githubusercontent.com/71985358/94372915-e8f69000-0101-11eb-9685-c5c6c377e82d.png)

**Comment by morris-stoll** [comment]
I'm getting the same error.
In my case the enhanced ore veins download is broken aswell.

**Comment by fibrils** [comment]
Mine keeps trying to install the Enhanced Ore Veins - 8.0.1 - Patch and then install fails after I download.

**Comment by jdsmith2816** [comment]
Fixed in 1.0.11
