### ISSUE TITLE
Can't craft Flintstock pistols

### ISSUE THREAD

**Issue by Naum31** [jdsmith2816/emw#9]
Pyrean Flintlock pistol doesn't show up in the forge even if you have the blueprint in your inventory, and the required handicraft skill. Could also be the same for other pistols. 

I also tried crafting it after getting the required materials, but still nothing. 

**Did you add any additional mods?**
Only mod I have added is Customizable Camera to tweak 3rd person view.

**Comment by jdsmith2816** [comment]
No longer an issue in 1.0.2 as I ditched the pistols.
