### ISSUE TITLE
Option for Headgear toggle on Player, NPC's, Dolls

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#90]
Please make Headgear toggle-able on Player, NPC's and Dolls..
![72850_20200928113212_1](https://user-images.githubusercontent.com/69637298/94416857-a7a4c580-017f-11eb-9070-66a60d003005.png)

**Comment by jdsmith2816** [comment]
Hey, thanks for reporting all these issues lately;  it's definitely much appreciated.  I just wanted to drop a quick note and let you know that... I dont update EMW often but I do scrub through the issue list each time I start the process and fix up as many as I can in the time I have. Thanks!

**Comment by jdsmith2816** [comment]
The issue with swashbuckler hat is that it shouldn't be showing hair... It's a simple fix.

**Comment by kratores85** [comment]
> Hey, thanks for reporting all these issues lately; it's definitely much appreciated. I just wanted to drop a quick note and let you know that... I dont update EMW often but I do scrub through the issue list each time I start the process and fix up as many as I can in the time I have. Thanks!

Yeah, you're welcome, just want to help you fixing the issues I found, so that your modlist will getting better and better - it's a masterpiece already ;) Thanks for fixing all the stuff :)

Ah okay.. yeah so the issue with the Tracker's hood is related to other things okay.. ;)

**Comment by jdsmith2816** [comment]
Actually there is no issue here... You're wearing the female version on a male.  You can transform that helmet at a crafting bench into the version for males.
