### ISSUE TITLE
The Beast got stuck - Fight doesn't start

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#93]
Last fight in Arena vs "The Beast" (Rhalata Questline): Can't move and Fight doesn't start.. 
The Beast walks into the air and gets stuck..

I found myself a workaround with "prid" and "moveto player" - the fight between Tharaêl and The Beast started.. So I was able to continue the quest.
![72850_20200930102325_1](https://user-images.githubusercontent.com/69637298/94666342-a3a6ae00-030d-11eb-958b-cb69db5eb6ae.png)

**Comment by jdsmith2816** [comment]
This is no longer an issue for the upcoming release.
