### ISSUE TITLE
Hair Clipping Problem on some NPC's

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#95]
![72850_20201002074453_1](https://user-images.githubusercontent.com/69637298/94891872-872c8200-0483-11eb-95b3-4329817a9075.png)

**Comment by kratores85** [comment]
Same Problem I saw on Nailaq (Qalian's Last Smile - Rhalata Questline) and i think Menhir Hûriyas (Long way to the Top - Golden Sickle Questline)
It seems like a general problem with this Hairstyle..

**Comment by Regret13** [comment]
![87fa527422df6dd196fbbd471fc063f2](https://user-images.githubusercontent.com/74215529/98625001-e2506080-22dc-11eb-9515-cf6befc9e864.png)
This is also kind of a problem with the hairstyles the base game offers. Believe the hairstyle pictured comes from KS Hairdos. Just installed that and switched it over and it doesn't have the bald spots. Other hairstyles are broken though.

**Comment by jdsmith2816** [comment]
This is no longer an issue for the upcoming release.
