### ISSUE TITLE
Please add "Realistic Humanoid Movement Speed" + Horse Speed #compatible

### ISSUE THREAD

**Issue by kratores85** [jdsmith2816/emw#97]
https://www.nexusmods.com/skyrim/mods/32229/?tab=posts&BH=7
Please use the optional file that includes adjusted horse speed (vanilla horse sprint is hardly noticable)
"Realistic Humanoid Movement Speed 1_03 With Horse speed modifiers"

One issue (Vanilla Bug with Marketplace house) is fixed already.. I had no issues and it's compatible - here's the list:
https://docs.google.com/spreadsheets/d/1H-z3QUA_IB8Kr1JUXyewSW0xVz0y40ic0tpqhtzAiIw/edit#gid=1882936259

It improves movement speed and also for horse in a realistic way :) - also works with the Qyran Stance - tested this already

**Comment by jdsmith2816** [comment]
I'm fine with movement as is.  Feel free to run this on your own if you want.
