### ISSUE TITLE
Please fix the ore veins patch mod it does not download and fails putting in manual does nothing

### ISSUE THREAD

**Issue by SexyDangers** [jdsmith2816/emw#98]
**Describe the bug**

**To Reproduce**

2. Do '...'

**Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.

**Modlist version**

**Did you add any additional mods?**

**Comment by Martneb** [comment]
So i checked the other downloads:
Every download after 1.0.4 is broken, either due to the Ore Veins patch or due to an Armor Pack not being a whitelisted download

**Comment by kvarga74** [comment]
I'm just trying to Download for the first time and having the same issue. Any update on a fix?

**Comment by Martneb** [comment]
As i wrote before you could try to download a previous version, and add the updated versions of other mods that were updated, however for me only version 1.0.4 worked

**Comment by jdsmith2816** [comment]
Resolved in upcoming 1.0.11 release
