### ISSUE TITLE
Set boni don't get dded when equipping Setarmor directly from a container!

### ISSUE THREAD

**Issue by Martneb** [jdsmith2816/emw#99]
Whenever you equip armor of a set directly from a container(Chest,etc.), the Setbonus doesn't appear and it becomes impossible to gain it back, breaking the Setbonus.

1. Take any Setarmor e.g. Swashbuckler set
2.Put it in any Chest,Sack,etc.
3. Equip it from chest by pressing Shift AND Equip/Take (For me it's E)
4. See your Set Armor Become Invalid for any futere Boni

Expected:
The armor gets equipped, the boni appear(On a vanilla Save after a short delay)

1.0.4 (Sorry wrong Version not x.10)

No, the bug happens with just the modlist

Add some set armor and watch your Setboni disappear
[Test-Savefile.zip](https://github.com/jdsmith2816/emw/files/5394390/Test-Savefile.zip)

**Comment by jdsmith2816** [comment]
That's unfortunate but this isnt' a problem that I'll be able to resolve.  That's either a vanilla skyrim limitation or a bug with the enderal set bonus implementation.
